name: Deploy Demo to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'samples/BlazorFastMarquee.Demo/**'
      - 'Components/**'
      - 'wwwroot/**'
      - '*.cs'
      - '*.razor'
      - 'BlazorFastMarquee.csproj'
      - '.github/workflows/deploy-demo.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore samples/BlazorFastMarquee.Demo/BlazorFastMarquee.Demo.csproj
      
    - name: Build library
      run: dotnet build BlazorFastMarquee.csproj --configuration Release --no-restore
      
    - name: Publish WASM app
      run: dotnet publish samples/BlazorFastMarquee.Demo/BlazorFastMarquee.Demo.csproj -c Release -o output
      
    - name: Update base path in index.html
      run: |
        # Update base href for GitHub Pages (repo name will be the path)
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        sed -i "s|<base href=\"/\" />|<base href=\"/${REPO_NAME}/\" />|g" output/wwwroot/index.html
        sed -i "s|<base href=\"/\">|<base href=\"/${REPO_NAME}/\">|g" output/wwwroot/index.html
        echo "Updated base href to /${REPO_NAME}/"
        
    - name: Add .nojekyll file
      run: touch output/wwwroot/.nojekyll
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: output/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
